"""Pack the painted sky strips into src/skies.js (CT.skies = {dusk, noon, ...}).

python tools/make_skies.py [--q 92]
Each strip: 2048x512 WebP data URI (wraps horizontally; covers -8..+40 degrees of elevation, as sky.js maps it),
plus the mean horizon colour (0..3 degrees) so sky.js can match the fog to the painting. Budget: <= 600 KB total.
"""
import argparse
import base64
import io
import os

from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(HERE, "..", "art", "skies")
OUT = os.path.join(HERE, "skies.js")
EL0, EL1 = -8.0, 40.0          # must match PAINT_EL0 / PAINT_EL1 in sky.js
W, H = 2048, 512

ap = argparse.ArgumentParser()
ap.add_argument("--q", type=int, default=92)
a = ap.parse_args()


def horizon_rgb(im):
    # rows for elevations 0..3 degrees (v measured from the bottom)
    def row(el):
        v = (el - EL0) / (EL1 - EL0)
        return int(round((1 - v) * (H - 1)))
    band = im.crop((0, row(3.0), W, row(0.0) + 1)).convert("RGB").resize((1, 1), Image.BOX)
    return "#%02x%02x%02x" % band.getpixel((0, 0))


def pack(q):
    entries, total = [], 0
    for name in ("dusk", "noon"):
        im = Image.open(os.path.join(ART, f"sky_{name}.png")).convert("RGB").resize((W, H), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, "WEBP", quality=q, method=6)
        b = buf.getvalue()
        total += len(b)
        uri = "data:image/webp;base64," + base64.b64encode(b).decode("ascii")
        entries.append(f"  {name}: '{uri}',\n  {name}Horizon: '{horizon_rgb(im)}',")
    return entries, total


q = a.q
entries, total = pack(q)
while total > 600_000 and q > 40:
    q -= 5
    entries, total = pack(q)
js = ("// ─── SKIES: painted horizon strips (generated by tools/make_skies.py; do not edit) ───\n"
      "window.CT = window.CT || {};\n"
      f"CT.skies = {{\n  el0: {EL0}, el1: {EL1},\n" + "\n".join(entries) + "\n};\n")
open(OUT, "w", encoding="utf-8").write(js)
print(f"wrote {os.path.normpath(OUT)}: webp q{q}, {total / 1024:.0f} KB of images, {len(js) / 1024:.0f} KB file")
