"""Convert the painted art textures into src/textures.js (CT.tex = {name: 'data:image/webp;base64,...'}).

python tools/make_textures.py [--q 78]
Tiles are 512x512 WebP; the foliage atlas (2x2 cut-outs: oak, pine, bush, birch) is 1024x1024 with alpha.
"""
import argparse
import base64
import io
import os

from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(HERE, "..", "art", "textures")
OUT = os.path.join(HERE, "textures.js")
TILES = {
    "grass": "meadow_grass.png", "road": "dirt_road.png", "cobble": "cobblestone.png", "rock": "rock_cliff.png",
    "wall": "timber_plaster_wall.png", "thatch": "thatch_roof.png", "tiles": "clay_roof_tiles.png",
    "planks": "wood_planks.png", "bark": "tree_bark.png",
}

ap = argparse.ArgumentParser()
ap.add_argument("--q", type=int, default=78)
a = ap.parse_args()


def webp(im, q, alpha=False):
    b = io.BytesIO()
    im.save(b, "WEBP", quality=q, method=6, exact=alpha)
    return b.getvalue()


def bleed(im):
    """Fill the RGB under transparent pixels with nearby colours so mipmaps do not get dark fringes."""
    rgb, al = im.convert("RGB"), im.split()[3]
    fill = rgb.copy()
    for r in (4, 16, 48):
        blur = Image.composite(rgb, fill, al.point(lambda v: 255 if v > 8 else 0)).filter(ImageFilter.GaussianBlur(r))
        fill = Image.composite(fill, blur, al.point(lambda v: 255 if v > 8 else 0))
    out = Image.composite(rgb, fill, al.point(lambda v: 255 if v > 8 else 0))
    out.putalpha(al)
    return out


parts, total = [], 0
for k, f in TILES.items():
    im = Image.open(os.path.join(ART, f)).convert("RGB").resize((512, 512), Image.LANCZOS)
    data = webp(im, a.q)
    total += len(data)
    parts.append(f"  {k}: 'data:image/webp;base64,{base64.b64encode(data).decode()}',")
fol = bleed(Image.open(os.path.join(ART, "foliage_atlas.png")).convert("RGBA").resize((1024, 1024), Image.LANCZOS))
data = webp(fol, a.q + 4, alpha=True)
total += len(data)
parts.append(f"  foliage: 'data:image/webp;base64,{base64.b64encode(data).decode()}',")
js = ("// Generated by tools/make_textures.py from art/textures (painted SDXL tiles). Do not edit by hand.\n"
      "// foliage atlas 2x2: oak (top-left), pine (top-right), bush (bottom-left), birch (bottom-right).\n"
      "window.CT = window.CT || {};\nCT.tex = {\n" + "\n".join(parts) + "\n};\n")
open(OUT, "w", encoding="utf-8").write(js)
print(f"wrote {os.path.normpath(OUT)}: {len(js) / 1e6:.2f} MB ({total / 1e6:.2f} MB binary, {len(parts)} textures)")
