"""Pack the horizon matte paintings into src/horizon.js (CT.horizon = {far_north, far_ring, mid_hills, + _noon}).

python tools/make_horizon.py [--q 92]
Far layers 2048x512, mid layer 2048x384, WebP with alpha, as data URIs. Budget: <= 900 KB total (quality drops until it fits).
"""
import argparse
import base64
import io
import os

from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(HERE, "..", "art", "horizon")
OUT = os.path.join(HERE, "horizon.js")
LAYERS = [("far_north", (2048, 512)), ("far_ring", (2048, 512)), ("mid_hills", (2048, 384))]
BUDGET = 900_000

ap = argparse.ArgumentParser()
ap.add_argument("--q", type=int, default=92)
a = ap.parse_args()


def pack(q):
    entries, total = [], 0
    for name, size in LAYERS:
        for suffix in ("", "_noon"):
            path = os.path.join(ART, f"{name}{suffix}.png")
            if not os.path.exists(path):
                continue
            im = Image.open(path).convert("RGBA").resize(size, Image.LANCZOS)
            buf = io.BytesIO()
            im.save(buf, "WEBP", quality=q, alpha_quality=90, method=6)
            b = buf.getvalue()
            total += len(b)
            entries.append(f"  {name}{suffix}: 'data:image/webp;base64,{base64.b64encode(b).decode('ascii')}',")
    return entries, total


q = a.q
entries, total = pack(q)
while total > BUDGET and q > 40:
    q -= 6
    entries, total = pack(q)
js = ("// ─── HORIZON: painted matte layers (generated by tools/make_horizon.py; do not edit) ───\n"
      "window.CT = window.CT || {};\nCT.horizon = {\n" + "\n".join(entries) + "\n};\n")
open(OUT, "w", encoding="utf-8").write(js)
print(f"wrote {os.path.normpath(OUT)}: webp q{q}, {len(entries)} layers, {total / 1024:.0f} KB of images, {len(js) / 1024:.0f} KB file")
